version: "3.7"

name: gift-service

services:
  gift-service-database:
    image: mongo
    restart: always
    ports:
      - ${MONGODB_PORT}:27017
    container_name: one-work-gift-engine-db
    environment:
      MONGO_INITDB_DATABASE: one-work-gift-engine
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ACCESS_KEY}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_SECRET_KEY}
    command: mongod --dbpath /data/db --port 27017
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - /home/deploy/onework-gift-service/db:/data/db
    networks:
      - gift-net

  gift-service-client:
    build:
      context: .
      dockerfile: ./client/Dockerfile.production
    container_name: one-work-gift-engine-client
    ports:
      - "12252:12252"
    restart: always
    env_file:
      - ./client/.env.production
    depends_on:
      - gift-service-server
    networks:
      - gift-net

  gift-service-server:
    build:
      context: .
      dockerfile: ./server/Dockerfile.production
    container_name: one-work-gift-engine-server
    ports:
      - "12250:12250"
      - "12251:12251"
    restart: always
    env_file:
      - ./server/.env.production
    depends_on:
      - gift-service-database
    networks:
      - gift-net

networks:
  gift-net:
    name: gift-net
    driver: bridge
